apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-lab-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devops-lab-api

  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1

  template:
    metadata:
      labels:
        app: devops-lab-api
    spec:
      containers:
        - name: api
          image: devops-lab-api:latest
          ports:
            - containerPort: 8000
          envFrom:
            - configMapRef:
                name: devops-lab-config
            - secretRef:
                name: devops-lab-secret
