apiVersion: v1
kind: Service
metadata:
  name: devops-lab-api
  labels:
    app: devops-lab-api
    release: prometheus
spec:
  type: ClusterIP
  selector:
    app: devops-lab-api
  ports:
    - name: http
      port: 8000
      targetPort: 8000
